### ISSUE TITLE
AR: deployment checklist

### ISSUE THREAD

**Issue by mhl** [mysociety/yournextrepresentative#417]
It might be helpful to have a series of things to check on the Yo Quiero Saber site before it's promoted, e.g.:

- [ ] Does sending of email from the host work correctly? `SERVER_EMAIL` and `SUPPORT_EMAIL` should be set to sensible values, and you should check that if someone registers for an account, they get the email asking them to confirm their email address.
- [ ] Are the various cron jobs enabled? You can base the crontab for the site [on `conf/crontab.ugly`](https://github.com/mysociety/yournextmp-popit/blob/master/conf/crontab.ugly) - errors from those jobs should be emailed to the MAILTO address defined in that file, so it's good to check that's working too.
- [ ] If the webserver is indexing `/media/` it's best to disable that.
- [ ] Check if the Twitter cards and Facebook OpenGraph data look right for a post page, the home page and a person page, at least.
- [ ] Check that the site is running in production mode, not debug mode
- [ ] Make sure that ALLOWED_HOSTS is set correctly
- [ ] `/static` and `/media` should be served directly by the webserver, since they're just static files
- [ ] Consider using the Varnish reverse proxy for caching (although the cache time of the front page may need to be dropped for Argentina, since the list of posts needing attention is randomly chosen)
- [ ] Some testing of the site in older versions of Internet Explorer would be worthwhile
- [ ] Make sure that Google Analytics is set up - usage data is important for funding applications in the future (see `GOOGLE_ANALYTICS_ACCOUNT` in `conf/general.yml`)
- [ ] Check that the ADMINS and MANAGERS email addresses work, since they'll get errors emailed to them
- [ ] Go through the Django deployment checklist (with some overlap with this list): https://docs.djangoproject.com/en/1.7/howto/deployment/checklist/
