### ISSUE TITLE
Make YNR a crowd-sourcing site for politicians

### ISSUE THREAD

**Issue by martinszy** [mysociety/yournextrepresentative#697]
Rationale: After elections are over, all YNR sites are useless until the next election. Allowing the sites to collect information on politicians is the way to keep sites alive.

- [ ] Create "nomination" model #698 
- [ ] Allow candidate to be with elections or nominations #699 
- [ ] Remove candidate's dependency on party (not all public servants belong to a party) #700 
- [ ] Rename "candidate" model to "politician" #701 
- [ ] Allow for flexibility in older elections and nominations #703

**Comment by tfgg** [comment]
This seems like a pretty big strategic change. Will this make the architecture of the site for its original purpose, crowd sourcing candidates during elections, more complex?

**Comment by martinszy** [comment]
@tfgg I don't think so. It will depend on the interface, but I'm guessing that adding nominations (past or current) will add complexity to a site as adding any other field would. And we could think of this feature as optional if someone is concerned.

**Comment by martinszy** [comment]
@tfgg I just re-read your comment and I see it refers to the architecture of the application.
This change will make the architecture a bit more complex, but that is not really the greatest concern.
Something we have to carefully consider is how to go about this change and avoid any complications for current instances. And to retain the ease of maintainability that this app has, not to add any more dependencies and avoid unreversable situations (like having to chose weather or not this site will have only candidates or only politicians). I think we have to dig deeper into the change to see if any situation like that will arise and handle it appropriately. 
I'm all ears for more specific concerns.

**Comment by tmtmtmtm** [comment]
@martinszy Can you expand a little on your rationale here? Why is it important / interesting / useful to "keep sites alive"? 

If the core concept of YNR is to gather information so that voters can make more informed decisions in an election, why does it matter if such a site becomes useless after the election? 

I think there's certainly value in being able to take the data from a YNR and use it in other ways post-election; and I think there might be potential to re-use some of the editing mechanisms in other contexts; but those both seem like quite different approaches, solving quite different problems. 

If the goal is simply to stop "YNR sites [being] useless until the next election", I'm not sure that having them simply "collect information on politicians" is necessarily the best approach (and certainly not the only one). So before getting _how_ to make that possible, I'd like to hear more about your vision for the _what_ and _why_.

**Comment by martinszy** [comment]
@tmtmtmtm 
1) why does it matter if such a site becomes useless after the election? 
It matters because the site is up, it has a community, and the community wants to continue working on it. This could not be the case everywhere, but it is the case here.

2) Elections are short, politicians have long careers, we want to follow them. This codebase is solid, useful and successful, that's why we think of extending this instead of doing another thing. We expect this changes to be useful for other instances and we don't want to fork.

3) I understand that it's not the only way to keep sites alive, but it's the one we think it would be most useful in the sense that everyone involved (citizens, devs, data journalists, etc) continue with similar tasks with a different focus, following the political moment. After elections not only the winners go to office, also a lot of other people that were not elected end up there and we can keep track of them.

**Comment by rusosnith** [comment]
1) why does it matter if such a site becomes useless after the election? 
We at cargografias.org could use the crowdsourced data from YNR. We gather data from actual politicians in charge in any part of the state, in any moment of history. We also use Popolo std, and I see YNR as a photograph, while Cargografias is the movie. This move @martinszy proposes could help bridge that gap!

**Comment by tmtmtmtm** [comment]
I'm still not understanding what the actual expected use is here for the site (as opposed to the data within it, which can happily be used anywhere post-election no matter what happens to the site).  I can see potential ways in which some of the underlying software could be repurposed into something more general, but that seems more like a matter of teasing those parts out into something that could be shared between YNR and that other platform, rather than turning YNR itself into something more abstract. 

At the minute YNR is going for the 'do one thing well' approach, and I suspect it's going to be hard enough generalising it to cope with different election systems that we haven't had to deal with yet, without extending it into a much broader, quite ill-defined, concept of tracking everyone holding public office. Premature abstraction like that has a very high potential of derailing the project entirely IMO.

**Comment by martinszy** [comment]
Moving this issue to the Conocimiento Abierto fork.
